version: '3.4'

services:
  php-fpm:
    build:
      context: .
      target: laravelapp_php
    depends_on:
      - db
      - redis

  nodejs:
    build:
      context: .
      target: laravelapp_nodejs
    depends_on:
      - php-fpm

  nginx:
    build:
      context: .
      target: laravelapp_nginx
    depends_on:
      - php-fpm
      - nodejs
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    container_name: laravelapp_db
    environment:
      - MYSQL_DATABASE=laravelapp
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"

  redis:
    image: redis:5-alpine
    container_name: laravelapp_redis
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
